const $=(id)=>document.getElementById(id);
const send=(m)=>new Promise(r=>chrome.runtime.sendMessage(m,r));
let data={hosts:{},secrets:[]}, selected=null;
const esc=(s)=>String(s??"").replace(/[&<>]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]));
const epCount=(h)=>Object.keys(h.endpoints||{}).length;
const secretsFor=(host)=>data.secrets.filter(s=>(s.source||"").includes(host));

function methodChip(m){
  const cls=m==="OPTIONS"?"m-OPT":("m-"+m);
  return `<span class="m ${cls}">${m==="OPTIONS"?"OPT":esc(m)}</span>`;
}
function methodsHtml(ep){
  const ms=Object.keys(ep.methods);
  return ms.length?`<div class="methods">${ms.map(methodChip).join("")}</div>`:`<div class="methods"><span class="m m-OPT">?</span></div>`;
}

function updateStats(){
  let ep=0; for(const h of Object.values(data.hosts)) ep+=epCount(h);
  $("sHosts").textContent=Object.keys(data.hosts).length;
  $("sEndpoints").textContent=ep;
  $("sSecrets").textContent=data.secrets.length;
}

function renderHosts(){
  const el=$("hosts"); el.innerHTML="";
  const hosts=Object.entries(data.hosts).sort((a,b)=>epCount(b[1])-epCount(a[1]));
  if(!hosts.length){el.innerHTML='<div class="empty" style="padding:24px">No hosts yet.</div>';return;}
  for(const [host,h] of hosts){
    const sc=secretsFor(host).length;
    const d=document.createElement("button");
    d.className="host"+(host===selected?" sel":"");
    d.innerHTML=`<span class="dot"></span><span><span class="name">${esc(host)}</span><span class="meta">${epCount(h)} endpoints${sc?` · <span class="s">${sc} secrets</span>`:""}</span></span>`;
    d.addEventListener("click",()=>{selected=host;renderHosts();renderContent();});
    el.appendChild(d);
  }
}

function renderContent(){
  const c=$("content");
  if(!selected||!data.hosts[selected]){c.innerHTML='<div class="empty">Browse with collecting on, then pick a host.</div>';return;}
  const h=data.hosts[selected];
  const f=($("search").value||"").toLowerCase();
  const eps=Object.entries(h.endpoints).filter(([p])=>!f||p.toLowerCase().includes(f)).sort((a,b)=>a[0].localeCompare(b[0]));
  const secrets=secretsFor(selected);

  let html=`<div class="panel-head"><span class="panel-id">HOST</span><h2 class="panel-name">${esc(selected)}</h2></div>`;
  html+=`<p class="section-head">Endpoints (${eps.length})</p>`;
  if(!eps.length) html+='<div class="empty">No endpoints match.</div>';
  else for(const [pat,ep] of eps){
    const params=Object.keys(ep.params);
    const tags=(ep.observed?'<span class="tag obs">observed</span>':"")+(ep.fromJs?'<span class="tag js">from JS</span>':"");
    const paramChips=params.length?params.map(p=>`<span class="chip">${esc(p)}</span>`).join(""):"";
    html+=`<div class="row">${methodsHtml(ep)}<div style="min-width:0;flex:1">
      <div class="path">${esc(pat)}</div>
      <div class="rmeta">${tags}${paramChips}<span style="color:var(--dim)">${ep.hits} hit${ep.hits===1?"":"s"}</span></div>
    </div></div>`;
  }

  html+=`<p class="section-head">Secrets (${secrets.length})</p>`;
  if(!secrets.length) html+='<div class="empty">None found on this host.</div>';
  else for(const s of secrets){
    html+=`<div class="cert"><div class="cert-badge"><span class="sev ${s.sev}">${s.sev}</span> ${esc(s.type)}</div>
      <div class="cert-sample"><code>${esc(s.sample)}</code></div>
      <div class="cert-note">${esc((s.source||"").replace(/^https?:\/\//,"").slice(0,80))}</div></div>`;
  }
  c.innerHTML=html;
}

// ---- exports ----
function toOpenAPI(host,h){
  const paths={};
  for(const [pat,ep] of Object.entries(h.endpoints)){
    const methods=Object.keys(ep.methods).length?Object.keys(ep.methods):["GET"];
    const pp=(pat.match(/\{[^}]+\}/g)||[]).map(m=>({name:m.slice(1,-1),in:"path",required:true,schema:{type:"string"}}));
    const qp=Object.keys(ep.params).map(k=>({name:k,in:"query",required:false,schema:{type:"string"}}));
    paths[pat]={};
    for(const m of methods) paths[pat][m.toLowerCase()]={summary:`${m} ${pat}`,parameters:[...pp,...qp],responses:{"200":{description:"OK"}}};
  }
  return {openapi:"3.0.0",info:{title:`${host} (discovered)`,version:"0.0.0",description:"Auto-generated by JS Recon. Unverified — endpoints and parameters are guesses."},servers:[{url:"https://"+host}],paths};
}
function toPostman(host,h){
  const items=[];
  for(const [pat,ep] of Object.entries(h.endpoints)){
    const methods=Object.keys(ep.methods).length?Object.keys(ep.methods):["GET"];
    const segs=pat.split("/").filter(Boolean).map(s=>s.replace(/^\{(.+)\}$/,":$1"));
    const variable=(pat.match(/\{([^}]+)\}/g)||[]).map(m=>({key:m.slice(1,-1),value:""}));
    const query=Object.keys(ep.params).map(k=>({key:k,value:""}));
    const rawQuery=query.length?"?"+query.map(q=>q.key+"=").join("&"):"";
    for(const m of methods) items.push({name:`${m} /${segs.join("/")}`,request:{method:m,header:[],url:{raw:`https://${host}/${segs.join("/")}${rawQuery}`,protocol:"https",host:host.split("."),path:segs,query,variable}}});
  }
  return {info:{name:`${host} (JS Recon)`,schema:"https://schema.getpostman.com/json/collection/v2.1.0/collection.json"},item:items};
}
function download(name,text,mime){const b=new Blob([text],{type:mime||"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=name;a.click();URL.revokeObjectURL(a.href);}
function flash(btn,label){const old=btn.textContent;btn.textContent=label;setTimeout(()=>btn.textContent=old,1400);}
const needHost=()=>{if(!selected){alert("Pick a host first.");return false;}return true;};

$("export").addEventListener("click",()=>{if(needHost())download(`openapi-${selected}.json`,JSON.stringify(toOpenAPI(selected,data.hosts[selected]),null,2));});
$("postman").addEventListener("click",()=>{if(needHost())download(`postman-${selected}.json`,JSON.stringify(toPostman(selected,data.hosts[selected]),null,2));});
$("copyUrls").addEventListener("click",async()=>{
  if(!needHost())return;
  const urls=[...new Set(Object.keys(data.hosts[selected].endpoints).map(p=>`https://${selected}${p}`))].sort();
  try{await navigator.clipboard.writeText(urls.join("\n"));flash($("copyUrls"),`Copied ${urls.length}`);}
  catch{download(`urls-${selected}.txt`,urls.join("\n"),"text/plain");}
});
$("exportAll").addEventListener("click",()=>download(`js-recon-${Date.now()}.json`,JSON.stringify(data,null,2)));
$("search").addEventListener("input",renderContent);
$("refresh").addEventListener("click",load);
$("theme").addEventListener("click",()=>window.__setTheme&&window.__setTheme(window.__theme()==="light"?"dark":"light"));
$("clear").addEventListener("click",async()=>{if(confirm("Clear all discovered data?")){await send({type:"CLEAR"});selected=null;load();}});

async function load(){
  const r=await send({type:"GET_DATA"}); data=r.data||{hosts:{},secrets:[]};
  if(selected&&!data.hosts[selected]) selected=null;
  updateStats(); renderHosts(); renderContent();
}
load();
setInterval(load,4000);
